baseURL = "https://codeless.ca/"
languageCode = "en-us"
title = "Codeless House"
theme = "temple"
copyright = "(c) 2019"
SectionPagesMenu = "main"
Paginate = 10
pygmentsStyle = "solarized-dark"
pygmentsCodeFences = true

[permalinks]
    posts = "/:year/:month/:slug/"
[params]
  # Enables the topmenu, which pulls from categories
  topmenu = "categories"
  # Builds a list page for each category given
  background_color_class = "bg-black"
[taxonomies]
  tag = "tags"
  category = "categories"
[author]
  name = "Erik"
  github = "biomaks"
  gaid = "UA-115476323-1"
  twitter = "biomehanik"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
